# Generated by Django 2.2.2 on 2019-09-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción: ')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria')),
            ],
        ),
    ]
