# Generated by Django 2.2.2 on 2019-09-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=400, verbose_name='Descripción: '),
        ),
    ]
