# Generated by Django 2.2.2 on 2019-09-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190902_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='descripcion',
        ),
    ]
