# Generated by Django 2.2.2 on 2019-09-02 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_articulo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(default='.', validators=[django.core.validators.MaxLengthValidator(600)]),
            preserve_default=False,
        ),
    ]
